install.packages('remotes')
remotes::install_version(package = "BiocManager", version = "1.30.18", upgrade="never")
remotes::install_version(package = "Cairo", version = "1.5-15", upgrade="never")
remotes::install_version(package = "circlize", version = "0.4.15", upgrade="never")
BiocManager::install(package = "clusterProfiler")  # , version = "4.4.1", upgrade="never")
BiocManager::install(package = "ComplexHeatmap")  # , version = "2.12.0", upgrade="never")
remotes::install_version(package = "cowplot", version = "1.1.1", upgrade="never")
remotes::install_version(package = "dendextend", version = "1.15.2", upgrade="never")
remotes::install_version(package = "dplyr", version = "1.0.9", upgrade="never")
remotes::install_version(package = "egg", version = "0.4.5", upgrade="never")
remotes::install_version(package = "factoextra", version = "1.0.7", upgrade="never")
remotes::install_version(package = "ggplot2", version = "3.3.6", upgrade="never")
remotes::install_version(package = "ggsci", version = "2.9", upgrade="never")
remotes::install_version(package = "gridExtra", version = "2.3", upgrade="never")
remotes::install_version(package = "gtools", version = "3.9.2", upgrade="never")
remotes::install_version(package = "Hmisc", version = "4.7-0", upgrade="never")
remotes::install_version(package = "httr", version = "1.4.3", upgrade="never")
remotes::install_version(package = "igraph", version = "1.3.1", upgrade="never")
remotes::install_version(package = "jsonlite", version = "1.8.0", upgrade="never")
remotes::install_version(package = "knitr", version = "1.39", upgrade="never")
remotes::install_version(package = "leidenAlg", version = "1.0.3", upgrade="never")
remotes::install_version(package = "magrittr", version = "2.0.3", upgrade="never")
remotes::install_version(package = "MCDA", version = "0.0.21", upgrade="never")
remotes::install_version(package = "networkD3", version = "0.4", upgrade="never")
remotes::install_version(package = "openxlsx", version = "4.2.5", upgrade="never")
BiocManager::install(package = "org.Mm.eg.db")  # , version = "3.15.0", upgrade="never")
BiocManager::install(package = "org.Hs.eg.db")  # , version = "3.15.0", upgrade="never")
remotes::install_version(package = "pheatmap", version = "1.0.12", upgrade="never")
remotes::install_version(package = "plotly", version = "4.10.0", upgrade="never")
remotes::install_version(package = "propr", version = "4.2.6", upgrade="never")
remotes::install_version(package = "purrr", version = "0.3.4", upgrade="never")
remotes::install_version(package = "RColorBrewer", version = "1.1-3", upgrade="never")
BiocManager::install(package = "RCy3")  # , version = "2.16.0", upgrade="never")
BiocManager::install(package = "ReactomePA")  # , version = "1.40.0", upgrade="never")
remotes::install_version(package = "readr", version = "2.1.2", upgrade="never")
remotes::install_version(package = "rlist", version = "0.4.6.2", upgrade="never")
remotes::install_version(package = "scales", version = "1.2.0", upgrade="never")
remotes::install_version(package = "stringi", version = "1.7.6", upgrade="never")
remotes::install_version(package = "tibble", version = "3.1.7", upgrade="never")
remotes::install_version(package = "tidyselect", version = "1.1.2", upgrade="never")
